### ISSUE TITLE
ui.Image segfault

### ISSUE THREAD

**Issue by cdamundsen** [mebaadwaheed/winup#17]
If I call ui.Image with just a src argument it works fine. If I use scale_to_height or scale_to_width it segfaults:

`ui.Image(src="Regeneration.jpg", scale_to_width=100),`
yields
`Segmentation fault: 11`

**Comment by mebaadwaheed** [comment]
Will fix when I'm stable I had a surgery 👍

**Comment by mebaadwaheed** [comment]
fixed hopefully in 2.5.1

**Comment by cdamundsen** [comment]
I installed v2.5.1 and am running it in Python 3.13 on Mac OS 15.5. 

`ui.Image(src="Regeneration.jpg", scale_to_width=100),`

still throws

`Segmentation fault: 11`

and 

`ui.Image(src="Regeneration.jpg"),`

does not
